version: "3"
services:
  postgres:
    container_name: postgres_con
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
 
  pgadmin:
    container_name: pgadmin_con
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: